services:
  mysql:
    image: 'mysql:8.2.0'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
